# Generated by Django 2.2 on 2020-10-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainList', '0003_mainlist_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
