# Generated by Django 2.2 on 2020-10-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotList', '0002_hotlist_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
